# The number of players which have to sleep independently from the percentage
# - If this is above the playercount in a world, all players in the world have to sleep.
minPlayers: 2
# The ratio of players which have to sleep
# - Set it to 1 or 100% to use the plugin and normal sleeping behavior, but with
#   the benefit of ignored functionality.
sleepPercentage: 0.5
# Speed of time for a smoother transition to the morning.
# - Set to 0 to disable this feature.
nightSpeed: 300
# The time (in MC ticks) at which BetterBeds should consider it night and allow
# players to rest in their beds.
# - Leave at default or change to what you like.
nightTicks: 12516
# The time (in MC ticks) at which BetterBeds should consider it day and allow
# players to rise from their beds.
# - Leave at default or change to what you like.
morningTicks: 0
# Message Configuration:
# - The text defines what message should display for the player.
#   - BetterBeds special fields:
#     use {player} for the sleeping players name
#     use {sleeping} for the count of the sleeping players
#     use {online} for the online playercount
#     use {percentage} for the percentage of sleeping players
#     use {more} to get the count of how many more players have to sleep to skip the night
# - The type defines who should get the message.
#   - Possible values:
#     NOONE - Don't display the message to anyone / disable the display of the message (NEW!)
#     PLAYER - Only the player who triggered a BetterBeds action
#     SLEEPING - Only players who lay in a bed
#     WORLD - Every player who is in the same world
#     SERVER - Every player on the server
msg:
    mobs:
        text: "&6You may not rest now, &c{player}&6, there are monsters nearby!"
        type: "PLAYER"
    noSleep:
        text: "&6You may not rest during the day, &c{player}&6."
        type: "PLAYER"
    sleep:
        text: "&c{player}&6 is now sleeping. &c{sleeping}/{online}&6 ({percentage}%)"
        type: "SLEEPING"
    leave:
        text: "&c{player}&6 is no longer sleeping. &c{sleeping}/{online}&6 ({percentage}%) &c{more}&6 more required!"
        type: "SLEEPING"
    wake:
        text: "&6Rise and shine!  Good morning everyone!"
        type: "WORLD"
    notify:
        text: "&c{sleeping/{online}}&6 ({percentage}%) of players have gone to bed.  Skipping the night!"
        type: "SLEEPING"
    notifyOnSingle:
        text: "&c{player}&6 has gone to bed. Skipping the night!"
        type: "SLEEPING"
