name: ${project.name}
main: com.lupinedream.betterbeds.BetterBeds
version: '${minecraft.plugin.version}'
api-version: 1.13
description: ${project.description}
author: LupineDream
authors: [NeoTiger, Phoenix616]
website:  https://github.com/loopyd/BetterBeds
commands:
   betterbedsreload:
      aliases: [bbreload]
      description: Reloads the config from the configfile.
      usage: /<command>
      permission: betterbeds.cmd.reload
      permission-message: You don't have the permission <permission>
permissions:
   betterbeds.cmd.reload:
      description: Gives permission to the reload command
      default: op
   betterbeds.ghost:
      description: Makes player to a ghost
      default: false
   betterbeds.ghost.buster:
      description: Some people think giving * is a good idea. This doesn't make them ghosts
      default: false
   betterbeds.sleep:
      description: Gives user ability to sleep
      default: true
   betterbeds.ignore:
      description: Users with this permission don't get calculated when they are online.
      default: false
